version: '3'
services:
  query:
    image: factorio-analytics:latest
    ports:
      -  "3001:3001"
    environment:
      - PG_CACHE_HOST=6.6.6.212
      - PG_CACHE_PORT=5432
      - PG_STORAGE_HOST=6.6.6.168
      - PG_STORAGE_PORT=5432
      - FACTORIO_USER=[User]
      - FACTORIO_TOKEN=[Token]
      - NAME=DockerTest
      - VARIANT=Worker
    network_mode: bridge
