version: '3'
services:
  query:
    image: factorio-analytics:latest
    ports:
      -  "3001:3001"
    environment:
      - PG_CACHE_HOST=6.6.6.212
      - PG_CACHE_PORT=5432
      - FACTORIO_USER=CharacterOverflow
      - FACTORIO_TOKEN=27ede956f491a45426cf7d0c6e3c04
      - NAME=DockerTest
      - VARIANT=Worker
    network_mode: host
